version: "3.2"

services:
  nacos:
    image: nacos/nacos-server:1.4.1
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - cloud-mysql-data:/var/lib/mysql
      - cloud-mysql-conf:/etc/mysql/conf.d
    ports:
      - "3307:3306"
  userservice:
    build: ./user-service
  orderservice:
    build: ./order-service
  gateway:
    build: ./gateway
    ports:
      - "10010:10010"

volumes:
  cloud-mysql-data:
  cloud-mysql-conf:
