server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3307/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice # orderservice 的服务名称
  cloud:
    nacos:
      server-addr: nacos:8848 # nacos 服务地址
      discovery:
        cluster-name: HZ
mybatis:
  type-aliases-package: com.youngzy.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.youngzy: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice